package com.example.demo.dto;

public enum OrderEvent {
    ORDER_CREATED,
    PAYMENT_INITIATED,
    PAYMENT_CONFIRMED,
    PAYMENT_FAILED,
    CUSTOMER_CANCELLATION,
    ORDER_PACKED,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    RETURN_REQUESTED,
    RETURN_APPROVED,
    REFUND_PROCESSED
}
